#!/bin/bash

set -ex

if [[ -z $1 ]];
then
  ENV=test venv/bin/python -m pytest \
    --capture=sys \
    --capture=fd \
    --cov=sqlalchemy_tools/ \
    -vv
else
  ENV=test venv/bin/python -m pytest \
    --capture=sys \
    --capture=fd \
    --cov=sqlalchemy_tools/ \
    -vv \
    -k $1
fi
